kind = "web"
previewPath = "/"
title = "Shopline"
version = "1.0.0"
id = "artifacts/shopline"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18982

[services.development]
run = "pnpm --filter @workspace/shopline run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/shopline", "run", "build" ]
publicDir = "artifacts/shopline/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18982"
BASE_PATH = "/"
